class globalfull {
  var name;
  globalfull(this.name);
}

List<globalfull> FullCountriesName = [
  globalfull("United Arab Emirates"),
  globalfull("Argentina"),
  globalfull("Austria"),
  globalfull("Australia"),
  globalfull("Belgium"),
  globalfull("Bulgaria"),
  globalfull("Brazil"),
  globalfull("Canada"),
  globalfull("Switzerland"),
  globalfull("China"),
  globalfull("Colombia"),
  globalfull("Cuba"),
  globalfull("The Czech Republic"),
  globalfull("Germany"),
  globalfull("Egypt"),
  globalfull("France"),
  globalfull("England"),
  globalfull("Greece"),
  globalfull("Hong Kong"),
  globalfull("Hungary"),
  globalfull("Indonesia"),
  globalfull("Ireland"),
  globalfull("Israel"),
  globalfull("Italy"),
  globalfull("Japan"),
  globalfull("South Korea"),
  globalfull("Lithuania"),
  globalfull("Latvia"),
  globalfull("Morocco"),
  globalfull("Mexico"),
  globalfull("Malaysia"),
  globalfull("Nigeria"),
  globalfull("Netherlands"),
  globalfull("Norway"),
  globalfull("New Zealand"),
  globalfull("Philippines"),
  globalfull("Poland"),
  globalfull("Portugal"),
  globalfull("Romania"),
  globalfull("Serbia"),
  globalfull("Russia"),
  globalfull("Saudi Arabia"),
  globalfull("Sweden"),
  globalfull("Singapore"),
  globalfull("Slovenia"),
  globalfull("Slovakia"),
  globalfull("Thailand"),
  globalfull("Turkey"),
  globalfull("Taiwan"),
  globalfull("Ukraine"),
  globalfull("United States"),
  globalfull("Venezuela"),
  globalfull("South Africa")
];
