class globalfull {
  var name;
  var shortname;
  globalfull(this.name, this.shortname);
}

List<globalfull> FullCountriesName = [
  globalfull("United Arab Emirates", "ae"),
  globalfull("Argentina", "ar"),
  globalfull("Austria", "at"),
  globalfull("Australia", "au"),
  globalfull("Belgium", "be"),
  globalfull("Bulgaria", "bg"),
  globalfull("Brazil", "br"),
  globalfull("Canada", "ca"),
  globalfull("Switzerland", "ch"),
  globalfull("China", "cn"),
  globalfull("Colombia", "co"),
  globalfull("Cuba", "cu"),
  globalfull("The Czech Republic", "cz"),
  globalfull("Germany", "de"),
  globalfull("Egypt", "eg"),
  globalfull("France", "fr"),
  globalfull("England", "gb"),
  globalfull("Greece", "gr"),
  globalfull("Hong Kong", "hk"),
  globalfull("Hungary", "hu"),
  globalfull("Indonesia", "id"),
  globalfull("Ireland", "ie"),
  globalfull("Israel", "il"),
  globalfull("India", "in"),
  globalfull("Italy", "it"),
  globalfull("Japan", "jp"),
  globalfull("South Korea", "kr"),
  globalfull("Lithuania", "lt"),
  globalfull("Latvia", "lv"),
  globalfull("Morocco", "ma"),
  globalfull("Mexico", "mx"),
  globalfull("Malaysia", "my"),
  globalfull("Nigeria", "ng"),
  globalfull("Netherlands", "nl"),
  globalfull("Norway", "no"),
  globalfull("New Zealand", "nz"),
  globalfull("Philippines", "ph"),
  globalfull("Poland", "pl"),
  globalfull("Portugal", "pt"),
  globalfull("Romania", "ro"),
  globalfull("Serbia", "rs"),
  globalfull("Russia", "ru"),
  globalfull("Saudi Arabia", "sa"),
  globalfull("Sweden", "se"),
  globalfull("Singapore", "sg"),
  globalfull("Slovenia", "si"),
  globalfull("Slovakia", "sk"),
  globalfull("Thailand", "th"),
  globalfull("Turkey", "tr"),
  globalfull("Taiwan", "tw"),
  globalfull("Ukraine", "ua"),
  globalfull("United States", "us"),
  globalfull("Venezuela", "ve"),
  globalfull("South Africa", "za")
];
